const List = [
		{
			ico : "/public/img/r360.png",
			href: "https://at.umeng.com/9PjW5D",
			title : "融360",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/bl.png",
			href: "https://at.umeng.com/mCiSbi",
			title : "好贷",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/br.png",
			href: "https://at.umeng.com/fqieme",
			title : "手机贷",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/t07.png",
			href: "listDetail.html?f=0",
			title : "小额贷款",
			desc : "",
			pan : "",
			bg : "#fffbcc"
		},
		{
			ico : "/public/img/t02.png",
			href: "listDetail.html?f=1",
			title : "工薪贷款",
			desc : "",
			pan : "",
			bg : "#dcebff"
		},
		{
			ico : "/public/img/t03.png",
			href: "listDetail.html?f=2",
			title : "身份贷款",
			desc : "",
			pan : "",
			bg : "#ffdcf9"
		},
		{
			ico : "/public/img/t05.png",
			href: "listDetail.html?f=3",
			title : "淘宝可贷",
			desc : "",
			pan : "",
			bg : "#ffecdc"
		},
		{
			ico : "/public/img/t01.png",
			href: "listDetail.html?f=4",
			title : "大额贷款",
			desc : "",
			pan : "",
			bg : "#ffe5dc"
		},
		{
			ico : "/public/img/t08.png",
			href: "listDetail.html?f=5",
			title : "校园贷款",
			desc : "",
			pan : "",
			bg : "#e3ffc4"
		},
		{
			ico : "/public/img/t06.png",
			href: "listDetail.html?f=6",
			title : "信用贷款",
			desc : "",
			pan : "",
			bg : "#dddcff"
		},
		{
			ico : "/public/img/t04.png",
			href: "listDetail.html?f=7",
			title : "随意贷款",
			desc : "",
			pan : "",
			bg : "#f1f1f1"
		},
		{
			ico : "/public/img/2000.png",
			href: "listDetail.html?f=8",
			title : "2000以内贷款",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/5000.png",
			href: "listDetail.html?f=9",
			title : "5000以内贷款",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/10000.png",
			href: "listDetail.html?f=10",
			title : "1000以内贷款",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/10000+.png",
			href: "listDetail.html?f=11",
			title : "10000以上贷款",
			desc : "",
			pan : "",
		},
		{
			ico : "/public/img/11.png",
			href: "https://at.umeng.com/9PjW5D",
			title : "融360",
			base : "81392210",
			desc : "超低利率，无抵押信用贷，1分钟申请",
			pan : "hot.png",
		},
		{
			ico : "/public/img/2.png",
			href: "https://at.umeng.com/mCiSbi",
			title : "好贷",
			base : "48371280",
			desc : "凭身份证，实时放款，额度高达30万",
			pan : "tui.png",
		},
		{
			ico : "/public/img/12.png",
			href: "https://at.umeng.com/fqieme",
			title : "手机贷",
			base : "23828530",
			desc : "资料少，授信简单，放款快",
			pan : "",
		},
		{
			ico : "/public/img/4.png",
			href: "https://at.umeng.com/9LvqCq",
			title : "卡牛贷",
			base : "1939210",
			desc : "额度高、贷款易，闪电审批效率高",
			pan : "",
		},
		{
			ico : "/public/img/7.png",
			href: "https://at.umeng.com/9z8b8z",
			title : "你我贷",
			base : "657260",
			desc : "有信用卡就能借，额度高达3万元",
			pan : "",
		},
		{
			ico : "/public/img/5.png",
			href: "https://at.umeng.com/1X1XDm",
			title : "快易花",
			base : "452234",
			desc : "万达快钱贷，线上秒批50000元",
			pan : "",
		},
		{
			ico : "/public/img/3.png",
			href: "https://at.umeng.com/9XzKDe",
			title : "及贷",
			base : "248480",
			desc : "短期应急，最高1万等你拿",
			pan : "",
		},
		{
			ico : "/public/img/8.png",
			href: "https://at.umeng.com/rqS1nq",
			title : "拍拍贷",
			base : "132817",
			desc : "3000-20万闪电申请，月费利率低至0.55%",
			pan : "",
		},
		{
			ico : "/public/img/9.png",
			href: "https://at.umeng.com/bmee8f",
			title : "平安i贷",
			base : "111969",
			desc : "极速放款，额度高达3万",
			pan : "",
		},
		{
			ico : "/public/img/6.png",
			href: "https://at.umeng.com/5HTLrq",
			title : "马上消金",
			base : "348482",
			desc : "最快3分钟批，无面签8000元到账",
			pan : "",
		},
		{
			ico : "/public/img/14.png",
			href: "https://at.umeng.com/WLjOjm",
			title : "现金侠",
			base : "225564",
			desc : "快速审批，不愁没钱花",
			pan : "",
		},
		{
			ico : "/public/img/13.png",
			href: "https://at.umeng.com/q09j8n",
			title : "现金借款",
			base : "243223",
			desc : "3分钟提交资料，3小时审核完毕",
			pan : "",
		},
		{
			ico : "/public/img/16.png",
			href: "https://at.umeng.com/L99Pbm",
			title : "信用钱包",
			base : "462370",
			desc : "只凭身份证，10分钟审核，高通过率",
			pan : "",
		},
		{
			ico : "/public/img/15.png",
			href: "https://at.umeng.com/1zSX9v",
			title : "小花钱包",
			base : "1058060",
			desc : "三步搞定，最高3万，最快3分钟",
			pan : "",
		},
		{
			ico : "/public/img/1.png",
			href: "https://at.umeng.com/fyCGja",
			title : "贷上钱",
			base : "427515",
			desc : "小额应急，上贷上钱，88秒放款",
			pan : "",
		}
]

export default List;